#!/bin/bash
tmp=$(exec acpi)
regex="Battery $1: +[A-Za-z]+, +[0-9]+%"
val=$( [[ "$tmp" =~ $regex ]] && echo $BASH_REMATCH)
if [[ -z "$val" || "$val" == "" ]] ; then
	echo "Disconnected"
	exit
fi
value=$( [[ "$val" =~ (('Fully')|('Full')|('Charging')|('Discharging')|('Unknown')|('unknown')) ]] && echo $BASH_REMATCH)
value=${value// /}
value=${value//Unknown/Idle}
echo $value
