#!/bin/bash
tmp=$(exec sensors *-isa-*)
regex="crit += +\+[0-9]+\.[0-9]+\°C"
val=$([[ $tmp =~ $regex ]] && echo $BASH_REMATCH)
val=${val//crit/}
val=${val// /}
val=${val//+/}
val=${val//=/}
val=${val//°C/}
echo $val

