#!/bin/bash
wget -q -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add - &&
echo "" >> /etc/apt/sources.list &&
echo "# Mopidy APT archive" >> /etc/apt/sources.list &&
echo "deb http://apt.mopidy.com/ stable main contrib non-free" >> /etc/apt/sources.list &&
echo "deb-src http://apt.mopidy.com/ stable main contrib non-free" >> /etc/apt/sources.list &&
apt-get update &&
apt-get install mopidy-spotify

