#!/bin/bash
#song_list_format="{%a - }{%t}|{$8%f$9}$R{$3(%l)$9}"
song_status_format="{{%a{ \"%b\"{ (%y)}} - }{%t}}|{%f}"
#song_library_format="{%n - }{%t}|{%f}"
#tag_editor_album_format="{(%y) }%b"
#
ncmpcpp --now-playing "{{%a{ \"%b\"{ (%y)}} - }{%t}}|{%f}"
