#!/bin/bash
if [ "$(pidof conky)" ]; then
    echo "Killing all conky sessions before starting new.."
    killall conky
    echo "Done!"
fi

conky -c ~/.conky/conkyrc &
sleep 1s
conky -c ~/.conky/conkyrc_grey &
sleep 1s
conky -c ~/.conky/conkyrc_grey_net &
sleep 1s

# Ugly hack to keep the powersave status in sync. For some reason it doesn't write the correct value to the respective file when doing executing powersave. This will do though.
powersave
